# - name: install Rust for buildbot user
#   shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable"
#   become: yes
#   become_user: buildbot

# - name: add thumbv7em-none-eabihf target to Rust
#   shell: "~/.cargo/bin/rustup target add thumbv7em-none-eabihf"
#   become: yes
#   become_user: buildbot

- name: add kitware repo key
  apt_key:
    url: https://apt.kitware.com/keys/kitware-archive-latest.asc
  become: yes

- name: add kitware apt repository
  apt_repository:
    repo: 'deb https://apt.kitware.com/ubuntu/ bionic main'
  become: yes

- name: update cmake
  apt:
    package: cmake
    state: latest
    update_cache: yes
  become: yes

- name: install gdb-multiarch
  apt:
    package: gdb-multiarch
    state: present
  become: yes

# - name: 