- apt:
    package:
      - python3
      - python3-dev
      - python3-pip
      - python-setuptools
      - python3-cryptography
      - aptitude
      - build-essential
      - libssl-dev
    state: present
  become: yes

- pip:
    executable: pip3
    name: buildbot-worker
    state: present
    extra_args: '-U'
  become: yes

- name: force reinstall of service_identity via pip3 to fix weird glitches
  pip:
    executable: pip3
    name: service_identity
    state: forcereinstall
  become: yes

- user:
    name: buildbot
    state: present
  become: yes

- shell: 'buildbot-worker create-worker ~/buildbot {{master_host}}:{{master_port}} {{worker_name}} {{worker_password}}'
  args:
    creates: /home/buildbot/buildbot
  become: yes
  become_user: buildbot

- template:
    src: "{{item}}"
    dest: "/home/buildbot/{{item}}"
    owner: buildbot
    group: buildbot
  become: yes
  with_items:
    - buildbot/info/admin
    - buildbot/info/host

- template:
    src: etc/systemd/system/buildbot-worker.service
    dest: /etc/systemd/system/buildbot-worker.service
    mode: 0644
    owner: root
    group: root
  become: yes

- systemd:
    name: buildbot-worker
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: yes

- name: install test dependencies
  import_tasks: install-test-deps.yml