- apt:
    package:
      - python3
      - python3-dev
      - python3-pip
      - python3-cryptography
      - aptitude
      - build-essential
      - libssl-dev
      - nginx
    state: present
  become: yes

- pip:
    executable: pip3
    name:
      - buildbot[tls] # buildbot master
      - buildbot-www
      - buildbot-waterfall-view
      - buildbot-console-view
      - buildbot-grid-view
    state: present
    extra_args: '-U'
  become: yes

- pip:
    executable: pip3
    name: service_identity
    state: forcereinstall
  become: yes

- user:
    name: buildmaster
    state: present
  become: yes

- shell: 'buildbot create-master -r ~/basedir'
  args:
    creates: /home/buildmaster/basedir
  become: yes
  become_user: buildmaster

- name: copy buildbot master config
  template:
    src: buildbot/master.cfg
    dest: /home/buildmaster/basedir/master.cfg
    owner: buildmaster
    group: buildmaster
  become: yes

- template:
    src: etc/systemd/system/buildbot-master.service
    dest: /etc/systemd/system/buildbot-master.service
    mode: 0644
    owner: root
    group: root
  become: yes

- systemd:
    name: buildbot-master
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: yes