- hosts: testbench
  tasks:
    - import_role: name=workbench-base
    - import_role: name=flashing # openocd and friends
    - import_role: name=buildbot-worker
      vars:
        master_host: ci.wisc.space
        master_port: 9989
        worker_name: testbench
        worker_password: "{{buildbot_passwords.testbench}}"

- hosts: jumpbox
  tasks:
    - import_role: name=jumpbox-base
    - import_role: name=buildbot-master
      vars:
        workers:
          - name: testbench
            password: "{{buildbot_passwords.testbench}}"
